apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map
  namespace: 5fca0307-07d5-4eb2-bfab-a1d4765c0107
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: dc-metro-map
status:
  loadBalancer: {}
